In [4]:
import numpy as np
import pandas as pd
nums = pd.DataFrame(np.random.randint(-100, 100, (3,3)), columns=["A","B","C"])

In [5]:
nums

    A   B   C
0 -27  54  36
1  40   9  54
2  19 -48   1

In [6]:
nums>10  # show which elements are > 0

       A      B      C
0  False   True   True
1   True  False   True
2   True  False  False

In [7]:
nums[nums>0]  # show which numbers are > 0

      A     B   C
0   NaN  54.0  36
1  40.0   9.0  54
2  19.0   NaN   1

In [8]:
nums[nums["B"]>0]  # show rows where col B > 0

    A   B   C
0 -27  54  36
1  40   9  54

In [9]:
nums[nums["B"]<0]["B"]  # shows rows in col C where col B > 0

2   -48
Name: B, dtype: int32

In [10]:
nums.loc[nums["B"]>0,["A","C"]] # another way to do the same thing

    A   C
0 -27  36
1  40  54

In [11]:
# fetch weather data from Environment Canada & clean it 
weather = pd.read_html("http://climate.weather.gc.ca/climate_data/daily_data_e.html?StationID=27174&timeframe"
                       + "=2&StartYear=1840&EndYear=2019&Day=11&Year=2019&Month=6#")[0]
weather.drop(index=[30,31,32,33],axis=0,inplace=True)
weather.drop(axis=1,columns=["Total Rain Definition mm","Snow on Grnd Definition cm"],inplace=True)
weather.fillna(0,inplace=True)
weather

,DAY,Max Temp Definition °C,Min Temp Definition °C,Mean Temp Definition °C,Heat Deg Days Definition,Cool Deg Days Definition,Total Snow Definition cm,Total Precip Definition mm,Dir of Max Gust Definition 10's deg,Spd of Max Gust Definition km/h
0,01,19.0,0.1,9.6,8.4,0.0,0,0.0,35,47
1,02,18.3,-0.6,8.9,9.1,0.0,0,0.0,11,34
2,03,27.1,10.8,18.9,0.0,0.9,0,2.6,12,55
3,04,27.0,10.8,18.9,0.0,0.9,0,0.0,35,45
4,05,26.3,4.9,15.6,2.4,0.0,0,0.0,2,39
5,06,27.7,10.8,19.2,0.0,1.2,0,0.0,6,35
6,07,36.6,18.9,27.7,0.0,9.7,0,2.8,23,81
7,08,25.7,11.3,18.5,0.0,0.5,0,7.3,19,56
8,09,20.3,9.7,15.0,3.0,0.0,0,1.5,30,49
9,10,19.7,5.5,12.6,5.4,0.0,0,0.0,30,40
10,11,20.4,3.6,12.0,6.0,0.0,0,0.0,1,52
11,12,20.7,1.0,10.8,7.2,0.0,0,0.0,0,0
12,13,26.3,10.1,18.2,0.0,0.2,0,0.0,21,38
13,14,26.2,14.6,20.4,0.0,2.4,0,0.0,4,39
14,15,20.8,10.8,15.8,2.2,0.0,0,0.0,11,42
15,16,16.5,10.5,13.5,4.5,0.0,0,4.0,5,35
16,17,21.1,11.9,16.5,1.5,0.0,0,2.0,0,0
17,18,24.5,11.0,17.7,0.3,0.0,0,0.0,0,0
18,19,27.6,7.9,17.8,0.2,0.0,0,0.0,0,0
19,20,28.2,10.1,19.2,0.0,1.2,0,0.0,15,60
20,21,26.6,12.0,19.3,0.0,1.3,0,1.1,13,58
21,22,23.4,14.6,19.0,0.0,1.0,0,3.4,15,50
22,23,25.1,12.8,19.0,0.0,1.0,0,0.0,18,42
23,24,27.3,9.9,18.6,0.0,0.6,0,0.0,29,33
24,25,26.4,13.3,19.9,0.0,1.9,0,0.0,29,48
25,26,28.4,12.4,20.4,0.0,2.4,0,0.0,29,42
26,27,29.3,12.5,20.9,0.0,2.9,0,0.0,0,0
27,28,30.7,11.7,21.2,0.0,3.2,0,0.0,0,0
28,29,27.8,17.2,22.5,0.0,4.5,0,0.3,14,66
29,30,31.9,18.3,25.1,0.0,7.1,0,0.0,27,55

In [12]:
weather[weather["Mean Temp Definition °C"]>20]

TypeError: '>' not supported between instances of 'str' and 'int'

In [16]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   DAY                                  30 non-null     object
 1   Max Temp Definition °C               30 non-null     object
 2   Min Temp Definition °C               30 non-null     object
 3   Mean Temp Definition °C              30 non-null     object
 4   Heat Deg Days Definition             30 non-null     object
 5   Cool Deg Days Definition             30 non-null     object
 6   Total Snow Definition cm             30 non-null     int64
 7   Total Precip Definition mm           30 non-null     object
 8   Dir of Max Gust Definition 10's deg  30 non-null     object
 9   Spd of Max Gust Definition km/h      30 non-null     object
dtypes: int64(1), object(9)
memory usage: 2.5+ KB

In [18]:
weather = weather.apply(pd.to_numeric)
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   DAY                                  30 non-null     int64
 1   Max Temp Definition °C               30 non-null     float64
 2   Min Temp Definition °C               30 non-null     float64
 3   Mean Temp Definition °C              30 non-null     float64
 4   Heat Deg Days Definition             30 non-null     float64
 5   Cool Deg Days Definition             30 non-null     float64
 6   Total Snow Definition cm             30 non-null     int64
 7   Total Precip Definition mm           30 non-null     float64
 8   Dir of Max Gust Definition 10's deg  30 non-null     int64
 9   Spd of Max Gust Definition km/h      30 non-null     int64
dtypes: float64(6), int64(4)
memory usage: 2.5 KB

In [20]:
degree_sign = '\N{degree sign}'
print(degree_sign)

°

In [32]:
# show days where mean temp > 15 and total precip > 0
#weather[(weather["Mean Temp Definition °C"]>15) & (weather["Total Precip Definition mm"]>0)]
weather[(weather["Mean Temp Definition \N{degree sign}C"]>15) & (weather["Total Precip Definition mm"]>0)]

,DAY,Max Temp Definition °C,Min Temp Definition °C,Mean Temp Definition °C,Heat Deg Days Definition,Cool Deg Days Definition,Total Snow Definition cm,Total Precip Definition mm,Dir of Max Gust Definition 10's deg,Spd of Max Gust Definition km/h
2,3,27.1,10.8,18.9,0.0,0.9,0,2.6,12,55
6,7,36.6,18.9,27.7,0.0,9.7,0,2.8,23,81
7,8,25.7,11.3,18.5,0.0,0.5,0,7.3,19,56
16,17,21.1,11.9,16.5,1.5,0.0,0,2.0,0,0
20,21,26.6,12.0,19.3,0.0,1.3,0,1.1,13,58
21,22,23.4,14.6,19.0,0.0,1.0,0,3.4,15,50
28,29,27.8,17.2,22.5,0.0,4.5,0,0.3,14,66